import 'dart:convert';
import 'dart:io';

import 'package:bishare/core/crypto/bse2.dart';
import 'package:bishare/features/room/data/room_e2e.dart';
import 'package:flutter_test/flutter_test.dart';

import 'helpers/rust_test_lib.dart';

/// Golden vectors generated by the web client (bishare-web
/// tools/room-e2e-vectors.ts from src/lib/rooms/e2e.ts) and cross-checked
/// against an independent HKDF/X25519/AES-GCM implementation. Matching them
/// byte for byte is what lets app and browser members share one room.
void main() {
  final v = jsonDecode(File('test/fixtures/room_e2e_vectors.json').readAsStringSync())
      as Map<String, dynamic>;
  final file = v['file'] as Map<String, dynamic>;
  final grant = v['grant'] as Map<String, dynamic>;
  final roomKey = RoomE2E.fromB64u(v['roomKey'] as String);
  final meta = file['meta'] as Map<String, dynamic>;
  final roomMeta = RoomFileMeta(
    name: meta['name'] as String,
    type: meta['type'] as String,
    size: meta['size'] as int,
    thumbnail: meta['thumbnail'] as String,
  );

  test('kid matches the web', () async {
    expect(await RoomE2E.keyId(roomKey), v['kid']);
  });

  test('file and meta keys match the web', () async {
    final keys = await RoomE2E.fileKeys(roomKey, RoomE2E.fromB64u(file['salt'] as String));
    expect(RoomE2E.b64u(keys.fileKey), file['fileKey']);
    expect(RoomE2E.b64u(keys.metaKey), file['metaKey']);
  });

  test('sealed metadata is byte-identical to the web', () async {
    final sealed = await RoomE2E.sealFile(
      roomKey,
      roomMeta,
      salt: RoomE2E.fromB64u(file['salt'] as String),
      nonce: RoomE2E.fromB64u(file['metaNonce'] as String),
    );
    expect(sealed.salt, file['salt']);
    expect(sealed.meta, file['encMeta']);
    expect(RoomE2E.b64u(sealed.fileKey), file['fileKey']);
  });

  test('opens metadata the web sealed', () async {
    final opened = await RoomE2E.openFile(roomKey, file['salt'] as String, file['encMeta'] as String);
    expect(opened.meta.name, roomMeta.name);
    expect(opened.meta.type, roomMeta.type);
    expect(opened.meta.size, roomMeta.size);
    expect(opened.meta.thumbnail, roomMeta.thumbnail);
  });

  test('a wrong room key does not open metadata', () async {
    final wrong = RoomE2E.newRoomKey();
    expect(
      () => RoomE2E.openFile(wrong, file['salt'] as String, file['encMeta'] as String),
      throwsA(isA<RoomKeyException>()),
    );
  });

  test('X25519 public keys match the web', () async {
    final joiner = await RoomE2E.newKeyPair(seed: RoomE2E.fromB64u(grant['joinerPriv'] as String));
    final granter = await RoomE2E.newKeyPair(seed: RoomE2E.fromB64u(grant['granterPriv'] as String));
    expect(joiner.publicKeyB64, grant['joinerPub']);
    expect(granter.publicKeyB64, grant['granterPub']);
  });

  test('a grant is byte-identical to the web, and opens', () async {
    final code = grant['code'] as String;
    final joiner = await RoomE2E.newKeyPair(seed: RoomE2E.fromB64u(grant['joinerPriv'] as String));
    final granter = await RoomE2E.newKeyPair(seed: RoomE2E.fromB64u(grant['granterPriv'] as String));
    final box = await RoomE2E.grant(
      roomKey,
      code,
      granter,
      joiner.publicKeyB64,
      nonce: RoomE2E.fromB64u(grant['nonce'] as String),
    );
    expect(box, grant['box']);
    final k = await RoomE2E.acceptGrant(code, joiner, granter.publicKeyB64, box, v['kid'] as String);
    expect(k, roomKey);
  });

  test('a grant for another room code or another kid is refused', () async {
    final joiner = await RoomE2E.newKeyPair(seed: RoomE2E.fromB64u(grant['joinerPriv'] as String));
    expect(
      () => RoomE2E.acceptGrant('OTHER', joiner, grant['granterPub'] as String, grant['box'] as String, v['kid'] as String),
      throwsA(isA<RoomKeyException>()),
    );
    expect(
      () => RoomE2E.acceptGrant(grant['code'] as String, joiner, grant['granterPub'] as String, grant['box'] as String, 'AAAAAAAAAAAAAAAAAAAAAA'),
      throwsA(isA<RoomKeyException>()),
    );
  });

  test('a fresh key pair round-trips a grant', () async {
    final a = await RoomE2E.newKeyPair();
    final b = await RoomE2E.newKeyPair();
    final k = RoomE2E.newRoomKey();
    final kid = await RoomE2E.keyId(k);
    final box = await RoomE2E.grant(k, 'ABCD', a, b.publicKeyB64);
    expect(await RoomE2E.acceptGrant('ABCD', b, a.publicKeyB64, box, kid), k);
  });

  group('BSE2 with the derived file key (Rust)', () {
    late bool rust;
    late Directory tmp;
    setUpAll(() async => rust = await initRustForTests());
    setUp(() async => tmp = await Directory.systemTemp.createTemp('room-e2e'));
    tearDown(() async => tmp.delete(recursive: true));

    test('opens the container a browser uploaded', () async {
      if (!rust) return markTestSkipped('no Rust build (cargo build --manifest-path rust/Cargo.toml)');
      final input = File('${tmp.path}/in.bse2')
        ..writeAsBytesSync(RoomE2E.fromB64u(file['container'] as String));
      final output = File('${tmp.path}/out.bin');
      await Bse2.decryptFile(
        input: input,
        output: output,
        key: RoomE2E.fromB64u(file['fileKey'] as String),
      );
      expect(RoomE2E.b64u(output.readAsBytesSync()), file['plaintext']);
    });

    test('seals a file the same key opens again', () async {
      if (!rust) return markTestSkipped('no Rust build (cargo build --manifest-path rust/Cargo.toml)');
      final plain = File('${tmp.path}/p.txt')..writeAsStringSync('room upload ' * 1000);
      final sealed = File('${tmp.path}/p.bse2');
      final back = File('${tmp.path}/p.out');
      final keys = await RoomE2E.fileKeys(roomKey, RoomE2E.random(16));
      await Bse2.encryptFile(input: plain, output: sealed, key: keys.fileKey);
      expect(await Bse2.sniff(sealed), isTrue);
      await Bse2.decryptFile(input: sealed, output: back, key: keys.fileKey);
      expect(back.readAsStringSync(), plain.readAsStringSync());
    });
  });
}
