import 'dart:convert';
import 'dart:typed_data';

import 'package:bishare/core/rust/rust_facade.dart';
import 'package:convert/convert.dart' show hex;
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

/// Proves the Dart→Rust FFI bridge reproduces the shared `bishare-protocol`
/// crate's crypto BYTE-FOR-BYTE — the golden values below are generated by
/// `rust/examples/golden.rs` from the same crate iOS/Android use. This is the
/// P0 exit-criterion "cross-platform test vectors green" at the Flutter boundary.
///
/// Runs as an integration_test because `RustLib.init()` needs the cargokit-built
/// native library, which is not on `flutter test`'s host path.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Golden vectors (from rust/examples/golden.rs).
  final key = Uint8List.fromList(List<int>.generate(32, (i) => i));
  final nonce = Uint8List.fromList(List<int>.generate(12, (i) => i));
  final pt = Uint8List.fromList(utf8.encode('BIShare cross-platform test vector'));
  const chunk0 =
      '000102030405060708090a0b054b8573a497a73bee33f8f8c2c40801e2a2e15b82167f085d1491a56b0c63c66e623f9e794f97a98205cb0b27157af11d24';
  const chunk1 =
      '000102030405060708090a0ae4919a286eaa2a8ab4336e2bb89bf638a0dbbe6526429e3a4a4f0bad6b9648c23ecf16cfba5fdc41ea16333b7dbc9d97f427';
  const apub = 'e06Qm75//kTEZaIgA31gjuNYl9Me+XLwf3SJLLD3PxM=';
  const bpub = 'D6poTtKIZ7l/Smot7l34zpdOdrcBjj8iocTPJnhXDyA=';
  const shared = '9ffee322ad64e3bf95f3dc3e6c979113af57b356ed7b7fb9cb6bfe4a55eba48c';
  const afp = 'D1 9B F3 F0 82 78 2C 87';

  testWidgets('FFI chunk encrypt/decrypt matches golden vectors', (t) async {
    await Rust.ensureInitialized();

    expect(hex.encode(Rust.encryptChunk(pt, key, 0, nonce)!), chunk0);
    expect(hex.encode(Rust.encryptChunk(pt, key, 1, nonce)!), chunk1);
    expect(
      Rust.decryptChunk(Uint8List.fromList(hex.decode(chunk0)), key, 0, nonce),
      equals(pt),
    );
  });

  testWidgets('FFI X25519 keys + ECDH + fingerprint match golden', (t) async {
    await Rust.ensureInitialized();
    final a = Rust.engineFromSeed(Uint8List.fromList(List.filled(32, 0x11)))!;
    final b = Rust.engineFromSeed(Uint8List.fromList(List.filled(32, 0x22)))!;

    expect(a.publicKeyBase64(), apub);
    expect(b.publicKeyBase64(), bpub);
    expect(hex.encode(a.deriveSharedKey(peerPublicKeyBase64: bpub)!), shared);
    expect(a.fingerprint(), afp);

    // Legacy 44-byte X.509 SPKI key derives the identical shared secret.
    const x509Prefix = [
      0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x6e, 0x03, 0x21, 0x00,
    ];
    final x509Apub = base64.encode([...x509Prefix, ...base64.decode(apub)]);
    expect(
      hex.encode(b.deriveSharedKey(peerPublicKeyBase64: x509Apub)!),
      shared,
    );
  });
}
