// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt_inner`, `encrypt_inner`

/// Fresh random 32-byte AES-256 key for one transfer.
Uint8List bse2GenerateKey() =>
    RustLib.instance.api.crateApiBse2Bse2GenerateKey();

/// URL-safe base64 (no padding) — the text after `#k=` in a share link.
String? bse2EncodeKey({required List<int> key}) =>
    RustLib.instance.api.crateApiBse2Bse2EncodeKey(key: key);

/// Inverse of [`bse2_encode_key`]; `None` unless it decodes to 32 bytes.
Uint8List? bse2DecodeKey({required String fragment}) =>
    RustLib.instance.api.crateApiBse2Bse2DecodeKey(fragment: fragment);

/// Exact container length for a plaintext of this size — what the uploader
/// must reserve, since the relay only ever sees ciphertext.
BigInt bse2CiphertextSize({required BigInt plaintextSize}) => RustLib
    .instance
    .api
    .crateApiBse2Bse2CiphertextSize(plaintextSize: plaintextSize);

/// True when `head` (the first bytes of a file) carries the container magic.
bool bse2IsContainer({required List<int> head}) =>
    RustLib.instance.api.crateApiBse2Bse2IsContainer(head: head);

/// Seal the file at `input_path` into a new container at `output_path` with a
/// fresh random salt. Runs on its own thread and returns at once; progress
/// streams through `sink`, and the stream closing without an error means the
/// output is complete and synced to disk. A failure is delivered INTO the
/// sink via `add_error` (FRB sink-fn rule — see `quic_send_file`), and the
/// partial output file is removed so a caller can never upload a stub.
Stream<Bse2Progress> bse2EncryptFile({
  required String inputPath,
  required String outputPath,
  required List<int> key,
}) => RustLib.instance.api.crateApiBse2Bse2EncryptFile(
  inputPath: inputPath,
  outputPath: outputPath,
  key: key,
);

/// Open the container at `input_path` into the plaintext file at
/// `output_path`. Same threading/error contract as [`bse2_encrypt_file`]; on
/// any failure (wrong key, tampering, truncation) the partial output is
/// removed — the caller never sees half a file reported as success.
Stream<Bse2Progress> bse2DecryptFile({
  required String inputPath,
  required String outputPath,
  required List<int> key,
}) => RustLib.instance.api.crateApiBse2Bse2DecryptFile(
  inputPath: inputPath,
  outputPath: outputPath,
  key: key,
);

/// Progress of a whole-file seal/open: plaintext bytes done out of total.
class Bse2Progress {
  final BigInt done;
  final BigInt total;

  const Bse2Progress({required this.done, required this.total});

  @override
  int get hashCode => done.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bse2Progress &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total;
}
