// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Fingerprint of a peer's base64 public key (no key exchange needed).
String? peerFingerprint({required String base64Key}) =>
    RustLib.instance.api.crateApiCryptoPeerFingerprint(base64Key: base64Key);

/// Random 12-byte base nonce for a file transfer session.
Uint8List generateBaseNonce() =>
    RustLib.instance.api.crateApiCryptoGenerateBaseNonce();

/// Lowercase hex SHA-256 of `data`.
String sha256Hex({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoSha256Hex(data: data);

/// Encrypt one chunk → `nonce(12) | ciphertext | tag(16)`.
///
/// **Async on purpose** (no `frb(sync)`): FRB dispatches this onto its Rust
/// worker-thread pool instead of the caller (main) isolate, so the Dart event
/// loop stays free to drive the socket while AES-256-GCM runs. That network↔crypto
/// overlap is what lifts encrypted TCP throughput from ~17 MB/s toward the
/// network-bound ~45 MB/s (see `_encryptedBody` / `_handleUpload`).
Future<Uint8List?> encryptChunk({
  required List<int> data,
  required List<int> key,
  required BigInt chunkIndex,
  required List<int> baseNonce,
}) => RustLib.instance.api.crateApiCryptoEncryptChunk(
  data: data,
  key: key,
  chunkIndex: chunkIndex,
  baseNonce: baseNonce,
);

/// Decrypt one chunk from combined form. **Async on purpose** — see
/// [`encrypt_chunk`]; runs on FRB's worker pool so decrypt overlaps socket recv.
Future<Uint8List?> decryptChunk({
  required List<int> data,
  required List<int> key,
  required BigInt chunkIndex,
  required List<int> baseNonce,
}) => RustLib.instance.api.crateApiCryptoDecryptChunk(
  data: data,
  key: key,
  chunkIndex: chunkIndex,
  baseNonce: baseNonce,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EncryptionEngine>>
abstract class EncryptionEngine implements RustOpaqueInterface {
  /// Derive the shared AES-256 key from a peer's base64 public key.
  Uint8List? deriveSharedKey({required String peerPublicKeyBase64});

  /// Visual fingerprint of our own public key.
  String fingerprint();

  /// Restore from a stored 32-byte private seed.
  static EncryptionEngine? fromSeed({required List<int> seed}) =>
      RustLib.instance.api.crateApiCryptoEncryptionEngineFromSeed(seed: seed);

  /// Generate a fresh key pair.
  static EncryptionEngine generate() =>
      RustLib.instance.api.crateApiCryptoEncryptionEngineGenerate();

  /// Raw 32-byte private seed for persistence.
  Uint8List privateSeed();

  /// Base64 of the raw 32-byte public key (goes into `DeviceInfo.publicKey`).
  String publicKeyBase64();
}
