// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `op_from_entry`

/// Frame a `BinaryManifestStart` JSON string as a ManifestStart (0x0C) frame.
/// Round-trips through the protocol struct so the wire payload is exactly what
/// the peer's decoder expects (unknown/misspelled fields fail here, not there).
Future<Uint8List> encodeManifestStart({required String startJson}) => RustLib
    .instance
    .api
    .crateApiManifestEncodeManifestStart(startJson: startJson);

/// Frame a `Vec<BinaryManifestEntry>` JSON string (one batch) as a
/// ManifestChunk (0x0D) frame.
Future<Uint8List> encodeManifestChunk({required String entriesJson}) => RustLib
    .instance
    .api
    .crateApiManifestEncodeManifestChunk(entriesJson: entriesJson);

/// Frame a `BinaryManifestDelta` JSON string as a ManifestDelta (0x0E) frame.
Future<Uint8List> encodeManifestDelta({required String deltaJson}) => RustLib
    .instance
    .api
    .crateApiManifestEncodeManifestDelta(deltaJson: deltaJson);

/// Decode one complete manifest frame (0x0C/0x0D/0x0E) into a
/// `{"type": "manifestStart"|"manifestChunk"|"manifestDelta", "payload": …}`
/// JSON string, validating the payload against its protocol struct.
Future<String> decodeManifestFrame({required List<int> bytes}) =>
    RustLib.instance.api.crateApiManifestDecodeManifestFrame(bytes: bytes);

/// Diff two manifests (`Vec<BinaryManifestEntry>` JSON ×2) into the
/// `Vec<DeltaOp>` JSON that transforms `local` into `remote`:
///
/// * **add** — path only in `remote`
/// * **modify** — path in both but size, sha256, mtime (or dir-ness) differ
/// * **delete** — path only in `local`
/// * **rename** — a delete+add pair with identical content (same `Some`
///   sha256 + same size) collapses into one op (`path` = old, `newPath` = new)
///
/// Ops are emitted adds → modifies → renames → deletes, each in input order,
/// so the result is deterministic.
Future<String> manifestDiff({
  required String localJson,
  required String remoteJson,
}) => RustLib.instance.api.crateApiManifestManifestDiff(
  localJson: localJson,
  remoteJson: remoteJson,
);
