// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'quic.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `cancels`, `clear_cancel`, `client_config`, `drain_to_file`, `is_cancelled`, `read_str`, `ring_provider`, `runtime`, `self_signed`, `server_config`, `servers`, `stream_recv`, `stream_send`, `transport_config`, `write_str`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SkipServerVerify`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `supported_verify_schemes`, `verify_server_cert`, `verify_tls12_signature`, `verify_tls13_signature`

/// Stop the QUIC server on [port], if one is running.
void quicStop({required int port}) =>
    RustLib.instance.api.crateApiQuicQuicStop(port: port);

/// Cancel the in-flight QUIC send tagged with [cancel_id].
void quicCancel({required String cancelId}) =>
    RustLib.instance.api.crateApiQuicQuicCancel(cancelId: cancelId);

/// Start a QUIC server on `[::]:port`, staging received files as `.part` files in
/// `save_dir`. Emits [QuicServerEvent]s to Dart; the first is `Ready` (or `Error`
/// on bind failure). Stop it with [quic_stop].
Stream<QuicServerEvent> quicServe({
  required int port,
  required String saveDir,
}) => RustLib.instance.api.crateApiQuicQuicServe(port: port, saveDir: saveDir);

/// Send one file to `host:port` over QUIC, reporting bytes-sent progress. Returns
/// total bytes sent once the receiver ACKs. `session_id`/`file_id` correlate the
/// transfer with the TCP `prepare` the sender did first.
Stream<BigInt> quicSendFile({
  required String host,
  required int port,
  required String cancelId,
  required String sessionId,
  required String fileId,
  required String senderAlias,
  required String senderFingerprint,
  required String filePath,
  required String fileName,
  required String fileType,
}) => RustLib.instance.api.crateApiQuicQuicSendFile(
  host: host,
  port: port,
  cancelId: cancelId,
  sessionId: sessionId,
  fileId: fileId,
  senderAlias: senderAlias,
  senderFingerprint: senderFingerprint,
  filePath: filePath,
  fileName: fileName,
  fileType: fileType,
);

@freezed
sealed class QuicServerEvent with _$QuicServerEvent {
  const QuicServerEvent._();

  /// The server is listening.
  const factory QuicServerEvent.ready() = QuicServerEvent_Ready;

  /// A file arrived, written to `temp_path`. Dart names/records it.
  const factory QuicServerEvent.received({
    required String sessionId,
    required String fileId,
    required String senderAlias,
    required String senderFingerprint,
    required String fileName,
    required String fileType,
    required String tempPath,
    required BigInt size,
  }) = QuicServerEvent_Received;

  /// Incremental receive progress, emitted while the body streams in so the
  /// receiver UI advances instead of sitting on "Starting…" until completion.
  const factory QuicServerEvent.progress({
    required String sessionId,
    required String fileId,
    required String fileName,
    required BigInt received,
    required BigInt total,
  }) = QuicServerEvent_Progress;

  /// A non-fatal receive error.
  const factory QuicServerEvent.error({required String message}) =
      QuicServerEvent_Error;
}
