// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'scanner.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// Walk `root`, hashing only files that changed vs `prior`, and stream
/// [`ScanEvent::Batch`]es followed by [`ScanEvent::Done`]. `batch_size` bounds
/// entries per batch (peak RAM); `stability_ms` defers files whose mtime is that
/// recent (partial writes). Runs on a dedicated thread and returns immediately;
/// a fatal error is delivered via `sink.add_error` (FRB sink-fn rule).
Stream<ScanEvent> scanAndHash({
  required String root,
  required List<FfiPriorEntry> prior,
  required int batchSize,
  required PlatformInt64 stabilityMs,
}) => RustLib.instance.api.crateApiScannerScanAndHash(
  root: root,
  prior: prior,
  batchSize: batchSize,
  stabilityMs: stabilityMs,
);

/// A prior manifest fact from Dart (a `SyncEntries` row) — lets the scanner skip
/// re-hashing files whose `(size, mtimeMs)` are unchanged.
class FfiPriorEntry {
  final String path;
  final BigInt size;
  final PlatformInt64 mtimeMs;
  final String sha256;

  const FfiPriorEntry({
    required this.path,
    required this.size,
    required this.mtimeMs,
    required this.sha256,
  });

  @override
  int get hashCode =>
      path.hashCode ^ size.hashCode ^ mtimeMs.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPriorEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size &&
          mtimeMs == other.mtimeMs &&
          sha256 == other.sha256;
}

/// One scanned entry crossing to Dart — mirrors
/// `bishare_protocol::binary::BinaryManifestEntry` so Dart can serialize a batch
/// straight into a manifest / `manifest_diff` input.
class FfiScanEntry {
  final String path;
  final BigInt size;
  final PlatformInt64 mtimeMs;

  /// Lowercase-hex SHA-256; `None` for directories and files skipped as
  /// unstable (still being written).
  final String? sha256;
  final bool isDir;

  const FfiScanEntry({
    required this.path,
    required this.size,
    required this.mtimeMs,
    this.sha256,
    required this.isDir,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      size.hashCode ^
      mtimeMs.hashCode ^
      sha256.hashCode ^
      isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiScanEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size &&
          mtimeMs == other.mtimeMs &&
          sha256 == other.sha256 &&
          isDir == other.isDir;
}

/// Final counters — emitted once, after the last [`ScanEvent::Batch`].
class FfiScanStats {
  final BigInt dirs;
  final BigInt files;
  final BigInt hashed;
  final BigInt reused;
  final BigInt unstable;
  final BigInt bytesHashed;
  final BigInt errors;

  const FfiScanStats({
    required this.dirs,
    required this.files,
    required this.hashed,
    required this.reused,
    required this.unstable,
    required this.bytesHashed,
    required this.errors,
  });

  @override
  int get hashCode =>
      dirs.hashCode ^
      files.hashCode ^
      hashed.hashCode ^
      reused.hashCode ^
      unstable.hashCode ^
      bytesHashed.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiScanStats &&
          runtimeType == other.runtimeType &&
          dirs == other.dirs &&
          files == other.files &&
          hashed == other.hashed &&
          reused == other.reused &&
          unstable == other.unstable &&
          bytesHashed == other.bytesHashed &&
          errors == other.errors;
}

@freezed
sealed class ScanEvent with _$ScanEvent {
  const ScanEvent._();

  const factory ScanEvent.batch(List<FfiScanEntry> field0) = ScanEvent_Batch;
  const factory ScanEvent.done(FfiScanStats field0) = ScanEvent_Done;
}
