// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Frame a `SignalEnvelope` JSON string as a MediaSignal (0x11) frame.
/// Round-trips through the protocol struct so the wire payload is exactly what
/// the peer's decoder expects (unknown/misspelled fields fail here, not there).
Future<Uint8List> encodeMediaSignal({required String envJson}) =>
    RustLib.instance.api.crateApiSignalEncodeMediaSignal(envJson: envJson);

/// Decode a complete MediaSignal (0x11) frame back into its `SignalEnvelope`
/// JSON string.
Future<String> decodeMediaSignal({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSignalDecodeMediaSignal(bytes: bytes);
