// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Path-safe a received filename (strips separators, `..`, control chars).
String sanitizeFilename({required String name}) =>
    RustLib.instance.api.crateApiUtilsSanitizeFilename(name: name);

/// Coarse category name for a MIME type (image/video/document/…).
String categoryName({required String mimeType}) =>
    RustLib.instance.api.crateApiUtilsCategoryName(mimeType: mimeType);

/// A 4-char room code (charset excludes I/O/0/1).
String roomCode() => RustLib.instance.api.crateApiUtilsRoomCode();

/// A transfer code.
String transferCode() => RustLib.instance.api.crateApiUtilsTransferCode();

/// Smart-rename an incoming file using the sender alias.
String smartName({required String originalName, required String senderAlias}) =>
    RustLib.instance.api.crateApiUtilsSmartName(
      originalName: originalName,
      senderAlias: senderAlias,
    );
